/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arraylistexercise2;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author rokom
 */
public class GUI extends javax.swing.JFrame {
    ArrayList <LibraryItem> libList = new ArrayList <LibraryItem>();
    private String name, desc, id, isbn, vol;
    private void add() {
        name = JOptionPane.showInputDialog(null, "Enter name: ");
        desc = JOptionPane.showInputDialog(null, "Enter description: ");
        id = JOptionPane.showInputDialog(null, "Enter id: ");
        if (booksRB.isSelected())
            isbn = JOptionPane.showInputDialog(null, "Enter ISBN: ");
        else
            vol = JOptionPane.showInputDialog(null, "Enter volume number: ");
        if (booksRB.isSelected()) {
            Books book = new Books();
            book.setName(name);
            book.setDesc(desc);
            book.setId(id);
            book.setIsbn(isbn);
            libList.add(book);
            outputTA.setText("Book added to array list.");
        }
        else {
            Journal journal = new Journal();
            journal.setName(name);
            journal.setDesc(desc);
            journal.setId(id);
            journal.setVol(vol);
            libList.add(journal);
            outputTA.setText("Journal added to array list.");
        }
    }
    private void save() {
        FileWriter fw;
        FileOutputStream fileOut;
        try {
            if (new File("library.data").exists()) {
                System.out.println("File already exists.");
                fileOut = new FileOutputStream("library.data", true);
                //ObjectOutputStream out = new ObjectOutputStream(fileOut);
                AppendableObjectOutputStream aOut = new AppendableObjectOutputStream(fileOut);
                for (LibraryItem item : libList) {
                    aOut.writeObject(item);
                }  
                aOut.close();
            }
            else {
                fileOut = new FileOutputStream("library.data");
                ObjectOutputStream out = new ObjectOutputStream(fileOut);
                for (LibraryItem item : libList) {
                out.writeObject(item);
                } 
                out.close();
            }
            fileOut.close();
            outputTA.setText("Data written to file.");
        }
        catch (IOException e) {
            System.out.println(e);
        }  
    }
    private void load() {
        ArrayList <LibraryItem> tempList = new ArrayList <LibraryItem>();
        outputTA.setText("");
        try {
            FileInputStream fileIn = new FileInputStream("library.data");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            while (fileIn.available() > 0) {
                try {
                    LibraryItem tempItem = (LibraryItem) in.readObject();
                    tempList.add(tempItem);
                }
                catch (ClassNotFoundException e) {
                    System.out.println(e);
                }
            }
            for (LibraryItem item : tempList) {
                outputTA.append(item.printDetails() + "\n");
            }
        }
        catch (FileNotFoundException e) {
            System.out.println(e);
        }
        catch (IOException f) {
            System.out.println(f);
        }      
    }
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        if (new File("library.data").exists())
            load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classBG = new javax.swing.ButtonGroup();
        addBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        loadBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        booksRB = new javax.swing.JRadioButton();
        journalRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addBTN.setText("Add");
        addBTN.setEnabled(false);
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        saveBTN.setText("Save");
        saveBTN.setEnabled(false);
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        loadBTN.setText("Load");
        loadBTN.setEnabled(false);
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });

        outputTA.setColumns(20);
        outputTA.setLineWrap(true);
        outputTA.setRows(5);
        jScrollPane1.setViewportView(outputTA);

        classBG.add(booksRB);
        booksRB.setText("Books");
        booksRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksRBActionPerformed(evt);
            }
        });

        classBG.add(journalRB);
        journalRB.setText("Journal");
        journalRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                journalRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadBTN)
                            .addComponent(saveBTN)
                            .addComponent(addBTN)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(booksRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(journalRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(addBTN)
                .addGap(31, 31, 31)
                .addComponent(saveBTN)
                .addGap(31, 31, 31)
                .addComponent(loadBTN)
                .addGap(35, 35, 35)
                .addComponent(booksRB)
                .addGap(18, 18, 18)
                .addComponent(journalRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_addBTNActionPerformed

    private void booksRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksRBActionPerformed
        // TODO add your handling code here:
        addBTN.setEnabled(true);
        saveBTN.setEnabled(true);
        loadBTN.setEnabled(true);
    }//GEN-LAST:event_booksRBActionPerformed

    private void journalRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_journalRBActionPerformed
        // TODO add your handling code here:
        addBTN.setEnabled(true);
        saveBTN.setEnabled(true);
        loadBTN.setEnabled(true);
    }//GEN-LAST:event_journalRBActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_saveBTNActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_loadBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JRadioButton booksRB;
    private javax.swing.ButtonGroup classBG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton journalRB;
    private javax.swing.JButton loadBTN;
    private javax.swing.JTextArea outputTA;
    private javax.swing.JButton saveBTN;
    // End of variables declaration//GEN-END:variables
}
